# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\MainControl_QA\TestDevelopment\TestCasePro\branches\working folder\lianjun.yao\TestCasePro_v1.0\UI\TestCase.ui'
#
# Created: Mon Aug 08 16:22:19 2016
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_TestCasePro(object):
    def setupUi(self, TestCasePro):
        TestCasePro.setObjectName(_fromUtf8("TestCasePro"))
        TestCasePro.resize(887, 657)
        TestCasePro.setMaximumSize(QtCore.QSize(1078, 751))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("Tc.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("Tc.ico")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        TestCasePro.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(TestCasePro)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.tabWidget_caseSelect = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget_caseSelect.setMinimumSize(QtCore.QSize(869, 550))
        self.tabWidget_caseSelect.setObjectName(_fromUtf8("tabWidget_caseSelect"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.tab)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.pushButton_cellectCancel = QtGui.QPushButton(self.tab)
        self.pushButton_cellectCancel.setObjectName(_fromUtf8("pushButton_cellectCancel"))
        self.gridLayout.addWidget(self.pushButton_cellectCancel, 1, 2, 1, 1)
        self.pushButton_importDir = QtGui.QPushButton(self.tab)
        self.pushButton_importDir.setObjectName(_fromUtf8("pushButton_importDir"))
        self.gridLayout.addWidget(self.pushButton_importDir, 0, 0, 1, 1)
        self.pushButton_selectAll = QtGui.QPushButton(self.tab)
        self.pushButton_selectAll.setObjectName(_fromUtf8("pushButton_selectAll"))
        self.gridLayout.addWidget(self.pushButton_selectAll, 0, 2, 1, 1)
        self.pushButton_removeDir = QtGui.QPushButton(self.tab)
        self.pushButton_removeDir.setObjectName(_fromUtf8("pushButton_removeDir"))
        self.gridLayout.addWidget(self.pushButton_removeDir, 1, 0, 1, 1)
        self.pushButton_expandTree = QtGui.QPushButton(self.tab)
        self.pushButton_expandTree.setObjectName(_fromUtf8("pushButton_expandTree"))
        self.gridLayout.addWidget(self.pushButton_expandTree, 0, 1, 1, 1)
        self.pushButton_retractTree = QtGui.QPushButton(self.tab)
        self.pushButton_retractTree.setObjectName(_fromUtf8("pushButton_retractTree"))
        self.gridLayout.addWidget(self.pushButton_retractTree, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.treeWidget_caseTree = QtGui.QTreeWidget(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeWidget_caseTree.sizePolicy().hasHeightForWidth())
        self.treeWidget_caseTree.setSizePolicy(sizePolicy)
        self.treeWidget_caseTree.setMinimumSize(QtCore.QSize(0, 440))
        self.treeWidget_caseTree.setMaximumSize(QtCore.QSize(370, 16777215))
        self.treeWidget_caseTree.setMouseTracking(False)
        self.treeWidget_caseTree.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.treeWidget_caseTree.setObjectName(_fromUtf8("treeWidget_caseTree"))
        self.treeWidget_caseTree.headerItem().setText(0, _fromUtf8("1"))
        self.treeWidget_caseTree.header().setVisible(False)
        self.verticalLayout.addWidget(self.treeWidget_caseTree)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(-1, 35, -1, 320)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.pushButton_add = QtGui.QPushButton(self.tab)
        self.pushButton_add.setMaximumSize(QtCore.QSize(39, 23))
        self.pushButton_add.setObjectName(_fromUtf8("pushButton_add"))
        self.verticalLayout_3.addWidget(self.pushButton_add)
        self.pushButton_removeOne = QtGui.QPushButton(self.tab)
        self.pushButton_removeOne.setMaximumSize(QtCore.QSize(39, 23))
        self.pushButton_removeOne.setObjectName(_fromUtf8("pushButton_removeOne"))
        self.verticalLayout_3.addWidget(self.pushButton_removeOne)
        self.pushButton_removeAll = QtGui.QPushButton(self.tab)
        self.pushButton_removeAll.setMaximumSize(QtCore.QSize(39, 23))
        self.pushButton_removeAll.setObjectName(_fromUtf8("pushButton_removeAll"))
        self.verticalLayout_3.addWidget(self.pushButton_removeAll)
        self.pushButton_up = QtGui.QPushButton(self.tab)
        self.pushButton_up.setMaximumSize(QtCore.QSize(39, 23))
        self.pushButton_up.setObjectName(_fromUtf8("pushButton_up"))
        self.verticalLayout_3.addWidget(self.pushButton_up)
        self.pushButton_down = QtGui.QPushButton(self.tab)
        self.pushButton_down.setMaximumSize(QtCore.QSize(39, 23))
        self.pushButton_down.setObjectName(_fromUtf8("pushButton_down"))
        self.verticalLayout_3.addWidget(self.pushButton_down)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_3)
        self.splitter = QtGui.QSplitter(self.tab)
        self.splitter.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.tableWidget_caseList = QtGui.QTableWidget(self.splitter)
        self.tableWidget_caseList.setMinimumSize(QtCore.QSize(500, 237))
        self.tableWidget_caseList.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableWidget_caseList.setProperty("showDropIndicator", False)
        self.tableWidget_caseList.setDragEnabled(False)
        self.tableWidget_caseList.setDragDropOverwriteMode(False)
        self.tableWidget_caseList.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.tableWidget_caseList.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableWidget_caseList.setRowCount(0)
        self.tableWidget_caseList.setObjectName(_fromUtf8("tableWidget_caseList"))
        self.tableWidget_caseList.setColumnCount(2)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_caseList.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_caseList.setHorizontalHeaderItem(1, item)
        self.tableWidget_caseList.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_caseList.verticalHeader().setDefaultSectionSize(22)
        self.tableWidget_caseList.verticalHeader().setMinimumSectionSize(18)
        self.layoutWidget = QtGui.QWidget(self.splitter)
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.layoutWidget)
        self.label.setMaximumSize(QtCore.QSize(16777215, 36))
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit_casePath = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_casePath.setObjectName(_fromUtf8("lineEdit_casePath"))
        self.horizontalLayout.addWidget(self.lineEdit_casePath)
        self.textBrowser_caseShow = QtGui.QTextBrowser(self.splitter)
        self.textBrowser_caseShow.setMinimumSize(QtCore.QSize(500, 237))
        self.textBrowser_caseShow.setObjectName(_fromUtf8("textBrowser_caseShow"))
        self.horizontalLayout_6.addWidget(self.splitter)
        self.tabWidget_caseSelect.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.tab_2)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.splitter_2 = QtGui.QSplitter(self.tab_2)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.tableWidget = QtGui.QTableWidget(self.splitter_2)
        self.tableWidget.setMinimumSize(QtCore.QSize(550, 467))
        self.tableWidget.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setDragEnabled(False)
        self.tableWidget.setDragDropOverwriteMode(False)
        self.tableWidget.setRowCount(0)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(3)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setDefaultSectionSize(23)
        self.horizontalLayout_8.addWidget(self.splitter_2)
        self.splitter_4 = QtGui.QSplitter(self.tab_2)
        self.splitter_4.setOrientation(QtCore.Qt.Vertical)
        self.splitter_4.setObjectName(_fromUtf8("splitter_4"))
        self.groupBox = QtGui.QGroupBox(self.splitter_4)
        self.groupBox.setMinimumSize(QtCore.QSize(267, 270))
        self.groupBox.setMaximumSize(QtCore.QSize(267, 270))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.layoutWidget1 = QtGui.QWidget(self.groupBox)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 20, 231, 192))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.gridLayout_2 = QtGui.QGridLayout(self.layoutWidget1)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.radioButton_HIL = QtGui.QRadioButton(self.layoutWidget1)
        self.radioButton_HIL.setChecked(True)
        self.radioButton_HIL.setObjectName(_fromUtf8("radioButton_HIL"))
        self.horizontalLayout_4.addWidget(self.radioButton_HIL)
        self.radioButton_SIL = QtGui.QRadioButton(self.layoutWidget1)
        self.radioButton_SIL.setObjectName(_fromUtf8("radioButton_SIL"))
        self.horizontalLayout_4.addWidget(self.radioButton_SIL)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 0, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.layoutWidget1)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.layoutWidget1)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.lineEdit_PLCIP = QtGui.QLineEdit(self.layoutWidget1)
        self.lineEdit_PLCIP.setObjectName(_fromUtf8("lineEdit_PLCIP"))
        self.gridLayout_2.addWidget(self.lineEdit_PLCIP, 1, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.layoutWidget1)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 2, 0, 1, 1)
        self.lineEdit_NIIP = QtGui.QLineEdit(self.layoutWidget1)
        self.lineEdit_NIIP.setObjectName(_fromUtf8("lineEdit_NIIP"))
        self.gridLayout_2.addWidget(self.lineEdit_NIIP, 3, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.layoutWidget1)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 3, 0, 1, 1)
        self.lineEdit_PLCPORT = QtGui.QLineEdit(self.layoutWidget1)
        self.lineEdit_PLCPORT.setObjectName(_fromUtf8("lineEdit_PLCPORT"))
        self.gridLayout_2.addWidget(self.lineEdit_PLCPORT, 2, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.layoutWidget1)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_2.addWidget(self.label_8, 4, 0, 1, 1)
        self.lineEdit_NIPORT = QtGui.QLineEdit(self.layoutWidget1)
        self.lineEdit_NIPORT.setObjectName(_fromUtf8("lineEdit_NIPORT"))
        self.gridLayout_2.addWidget(self.lineEdit_NIPORT, 4, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.layoutWidget1)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_2.addWidget(self.label_10, 5, 0, 1, 1)
        self.comboBox_paramName = QtGui.QComboBox(self.layoutWidget1)
        self.comboBox_paramName.setObjectName(_fromUtf8("comboBox_paramName"))
        self.gridLayout_2.addWidget(self.comboBox_paramName, 5, 1, 1, 1)
        self.layoutWidget2 = QtGui.QWidget(self.groupBox)
        self.layoutWidget2.setGeometry(QtCore.QRect(40, 220, 158, 25))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_7.setMargin(0)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.pushButton_getConfig = QtGui.QPushButton(self.layoutWidget2)
        self.pushButton_getConfig.setObjectName(_fromUtf8("pushButton_getConfig"))
        self.horizontalLayout_7.addWidget(self.pushButton_getConfig)
        self.pushButton_saveConfig = QtGui.QPushButton(self.layoutWidget2)
        self.pushButton_saveConfig.setObjectName(_fromUtf8("pushButton_saveConfig"))
        self.horizontalLayout_7.addWidget(self.pushButton_saveConfig)
        self.layoutWidget3 = QtGui.QWidget(self.splitter_4)
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.gridLayout_5 = QtGui.QGridLayout(self.layoutWidget3)
        self.gridLayout_5.setMargin(0)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.pushButton_getCase = QtGui.QPushButton(self.layoutWidget3)
        self.pushButton_getCase.setMinimumSize(QtCore.QSize(150, 31))
        self.pushButton_getCase.setObjectName(_fromUtf8("pushButton_getCase"))
        self.gridLayout_5.addWidget(self.pushButton_getCase, 0, 0, 1, 1)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.pushButton_start = QtGui.QPushButton(self.layoutWidget3)
        self.pushButton_start.setMaximumSize(QtCore.QSize(151, 31))
        self.pushButton_start.setObjectName(_fromUtf8("pushButton_start"))
        self.gridLayout_3.addWidget(self.pushButton_start, 0, 0, 1, 1)
        self.splitter_3 = QtGui.QSplitter(self.layoutWidget3)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName(_fromUtf8("splitter_3"))
        self.pushButton_pause = QtGui.QPushButton(self.splitter_3)
        self.pushButton_pause.setMaximumSize(QtCore.QSize(72, 23))
        self.pushButton_pause.setObjectName(_fromUtf8("pushButton_pause"))
        self.pushButton_stop = QtGui.QPushButton(self.splitter_3)
        self.pushButton_stop.setMaximumSize(QtCore.QSize(73, 23))
        self.pushButton_stop.setObjectName(_fromUtf8("pushButton_stop"))
        self.gridLayout_3.addWidget(self.splitter_3, 1, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_3, 1, 0, 1, 1)
        self.pushButton_report = QtGui.QPushButton(self.layoutWidget3)
        self.pushButton_report.setMinimumSize(QtCore.QSize(150, 31))
        self.pushButton_report.setObjectName(_fromUtf8("pushButton_report"))
        self.gridLayout_5.addWidget(self.pushButton_report, 2, 0, 1, 1)
        self.horizontalLayout_8.addWidget(self.splitter_4)
        self.tabWidget_caseSelect.addTab(self.tab_2, _fromUtf8(""))
        self.verticalLayout_2.addWidget(self.tabWidget_caseSelect)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.pushButton_back = QtGui.QPushButton(self.centralwidget)
        self.pushButton_back.setMaximumSize(QtCore.QSize(75, 23))
        self.pushButton_back.setObjectName(_fromUtf8("pushButton_back"))
        self.horizontalLayout_2.addWidget(self.pushButton_back)
        self.pushButton_next = QtGui.QPushButton(self.centralwidget)
        self.pushButton_next.setMaximumSize(QtCore.QSize(75, 23))
        self.pushButton_next.setObjectName(_fromUtf8("pushButton_next"))
        self.horizontalLayout_2.addWidget(self.pushButton_next)
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setMaximumSize(QtCore.QSize(431, 41))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.label_progress = QtGui.QLabel(self.frame)
        self.label_progress.setMaximumSize(QtCore.QSize(60, 14))
        self.label_progress.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_progress.setObjectName(_fromUtf8("label_progress"))
        self.gridLayout_6.addWidget(self.label_progress, 0, 2, 1, 1)
        self.label_unexecuted = QtGui.QLabel(self.frame)
        self.label_unexecuted.setMaximumSize(QtCore.QSize(36, 14))
        self.label_unexecuted.setText(_fromUtf8(""))
        self.label_unexecuted.setObjectName(_fromUtf8("label_unexecuted"))
        self.gridLayout_6.addWidget(self.label_unexecuted, 0, 8, 1, 1)
        self.label_pass = QtGui.QLabel(self.frame)
        self.label_pass.setMaximumSize(QtCore.QSize(30, 14))
        self.label_pass.setText(_fromUtf8(""))
        self.label_pass.setObjectName(_fromUtf8("label_pass"))
        self.gridLayout_6.addWidget(self.label_pass, 0, 4, 1, 1)
        self.label_16 = QtGui.QLabel(self.frame)
        self.label_16.setMaximumSize(QtCore.QSize(80, 14))
        self.label_16.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_6.addWidget(self.label_16, 0, 7, 1, 1)
        self.label_faild = QtGui.QLabel(self.frame)
        self.label_faild.setMaximumSize(QtCore.QSize(35, 14))
        self.label_faild.setText(_fromUtf8(""))
        self.label_faild.setObjectName(_fromUtf8("label_faild"))
        self.gridLayout_6.addWidget(self.label_faild, 0, 6, 1, 1)
        self.label_17 = QtGui.QLabel(self.frame)
        self.label_17.setMaximumSize(QtCore.QSize(30, 14))
        self.label_17.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_6.addWidget(self.label_17, 0, 5, 1, 1)
        self.label_totalCaseCount = QtGui.QLabel(self.frame)
        self.label_totalCaseCount.setMaximumSize(QtCore.QSize(90, 14))
        self.label_totalCaseCount.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_totalCaseCount.setObjectName(_fromUtf8("label_totalCaseCount"))
        self.gridLayout_6.addWidget(self.label_totalCaseCount, 0, 0, 1, 1)
        self.label_18 = QtGui.QLabel(self.frame)
        self.label_18.setMaximumSize(QtCore.QSize(30, 14))
        self.label_18.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_6.addWidget(self.label_18, 0, 3, 1, 1)
        self.label_12 = QtGui.QLabel(self.frame)
        self.label_12.setMaximumSize(QtCore.QSize(60, 14))
        self.label_12.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_6.addWidget(self.label_12, 0, 1, 1, 1)
        self.horizontalLayout_9.addLayout(self.gridLayout_6)
        self.horizontalLayout_2.addWidget(self.frame)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        TestCasePro.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(TestCasePro)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 887, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu = QtGui.QMenu(self.menubar)
        self.menu.setObjectName(_fromUtf8("menu"))
        self.menu_2 = QtGui.QMenu(self.menubar)
        self.menu_2.setObjectName(_fromUtf8("menu_2"))
        TestCasePro.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(TestCasePro)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        TestCasePro.setStatusBar(self.statusbar)
        self.action_getconfig = QtGui.QAction(TestCasePro)
        self.action_getconfig.setObjectName(_fromUtf8("action_getconfig"))
        self.action_saveconfig = QtGui.QAction(TestCasePro)
        self.action_saveconfig.setObjectName(_fromUtf8("action_saveconfig"))
        self.action_close = QtGui.QAction(TestCasePro)
        self.action_close.setObjectName(_fromUtf8("action_close"))
        self.actionHIL = QtGui.QAction(TestCasePro)
        self.actionHIL.setCheckable(True)
        self.actionHIL.setObjectName(_fromUtf8("actionHIL"))
        self.actionSIL = QtGui.QAction(TestCasePro)
        self.actionSIL.setCheckable(True)
        self.actionSIL.setObjectName(_fromUtf8("actionSIL"))
        self.action_5 = QtGui.QAction(TestCasePro)
        self.action_5.setObjectName(_fromUtf8("action_5"))
        self.action_Version = QtGui.QAction(TestCasePro)
        self.action_Version.setObjectName(_fromUtf8("action_Version"))
        self.action_log = QtGui.QAction(TestCasePro)
        self.action_log.setObjectName(_fromUtf8("action_log"))
        self.action_cleanlog = QtGui.QAction(TestCasePro)
        self.action_cleanlog.setObjectName(_fromUtf8("action_cleanlog"))
        self.menu.addAction(self.action_getconfig)
        self.menu.addAction(self.action_saveconfig)
        self.menu.addAction(self.action_close)
        self.menu_2.addAction(self.action_Version)
        self.menu_2.addAction(self.action_log)
        self.menu_2.addAction(self.action_cleanlog)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(TestCasePro)
        self.tabWidget_caseSelect.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(TestCasePro)

    def retranslateUi(self, TestCasePro):
        TestCasePro.setWindowTitle(_translate("TestCasePro", "TestCasePro", None))
        self.pushButton_cellectCancel.setText(_translate("TestCasePro", "取消全选", None))
        self.pushButton_importDir.setText(_translate("TestCasePro", "导入路径", None))
        self.pushButton_selectAll.setText(_translate("TestCasePro", "全选", None))
        self.pushButton_removeDir.setText(_translate("TestCasePro", "刷新路径", None))
        self.pushButton_expandTree.setText(_translate("TestCasePro", "展开", None))
        self.pushButton_retractTree.setText(_translate("TestCasePro", "收起", None))
        self.pushButton_add.setText(_translate("TestCasePro", "+", None))
        self.pushButton_removeOne.setText(_translate("TestCasePro", "-", None))
        self.pushButton_removeAll.setText(_translate("TestCasePro", "清空", None))
        self.pushButton_up.setText(_translate("TestCasePro", "↑", None))
        self.pushButton_down.setText(_translate("TestCasePro", "↓", None))
        item = self.tableWidget_caseList.horizontalHeaderItem(0)
        item.setText(_translate("TestCasePro", "用例名", None))
        item = self.tableWidget_caseList.horizontalHeaderItem(1)
        item.setText(_translate("TestCasePro", "用例地址", None))
        self.label.setText(_translate("TestCasePro", "路径：", None))
        self.tabWidget_caseSelect.setTabText(self.tabWidget_caseSelect.indexOf(self.tab), _translate("TestCasePro", "用例加载", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("TestCasePro", "用例名", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("TestCasePro", "执行结果", None))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("TestCasePro", "位置", None))
        self.groupBox.setTitle(_translate("TestCasePro", "配置", None))
        self.radioButton_HIL.setText(_translate("TestCasePro", "HIL     ", None))
        self.radioButton_SIL.setText(_translate("TestCasePro", "SIL     ", None))
        self.label_4.setText(_translate("TestCasePro", "PLC IP：", None))
        self.label_3.setText(_translate("TestCasePro", "测试平台：", None))
        self.label_7.setText(_translate("TestCasePro", "PORT：", None))
        self.label_5.setText(_translate("TestCasePro", "NI IP：", None))
        self.label_8.setText(_translate("TestCasePro", "PORT：", None))
        self.label_10.setText(_translate("TestCasePro", "映射文件", None))
        self.pushButton_getConfig.setText(_translate("TestCasePro", "读取配置", None))
        self.pushButton_saveConfig.setText(_translate("TestCasePro", "保存配置", None))
        self.pushButton_getCase.setText(_translate("TestCasePro", "获取用例", None))
        self.pushButton_start.setText(_translate("TestCasePro", "运 行", None))
        self.pushButton_pause.setText(_translate("TestCasePro", "暂停", None))
        self.pushButton_stop.setText(_translate("TestCasePro", "停止", None))
        self.pushButton_report.setText(_translate("TestCasePro", "查看报告", None))
        self.tabWidget_caseSelect.setTabText(self.tabWidget_caseSelect.indexOf(self.tab_2), _translate("TestCasePro", "用例执行", None))
        self.pushButton_back.setText(_translate("TestCasePro", "上一步", None))
        self.pushButton_next.setText(_translate("TestCasePro", "下一步", None))
        self.label_progress.setText(_translate("TestCasePro", "/", None))
        self.label_16.setText(_translate("TestCasePro", "未执行和异常：", None))
        self.label_17.setText(_translate("TestCasePro", "失败：", None))
        self.label_totalCaseCount.setText(_translate("TestCasePro", "共计  个用例   ", None))
        self.label_18.setText(_translate("TestCasePro", "成功：", None))
        self.label_12.setText(_translate("TestCasePro", "执行进度：", None))
        self.menu.setTitle(_translate("TestCasePro", "开始", None))
        self.menu_2.setTitle(_translate("TestCasePro", "帮助", None))
        self.action_getconfig.setText(_translate("TestCasePro", "读取配置", None))
        self.action_saveconfig.setText(_translate("TestCasePro", "保存配置", None))
        self.action_close.setText(_translate("TestCasePro", "关闭", None))
        self.actionHIL.setText(_translate("TestCasePro", "HIL", None))
        self.actionSIL.setText(_translate("TestCasePro", "SIL", None))
        self.action_5.setText(_translate("TestCasePro", "配置", None))
        self.action_Version.setText(_translate("TestCasePro", "Version", None))
        self.action_log.setText(_translate("TestCasePro", "日志文件", None))
        self.action_cleanlog.setText(_translate("TestCasePro", "清除日志", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    TestCasePro = QtGui.QMainWindow()
    ui = Ui_TestCasePro()
    ui.setupUi(TestCasePro)
    TestCasePro.show()
    sys.exit(app.exec_())

